;---------------------------------------------------------------------------------------------------
;      _____  .__       .__                       
;     /     \ |__| ____ |__| _____ _____  ______  
;    /  \ /  \|  |/    \|  |/     \\__  \ \____ \ 
;   /    Y    \  |   |  \  |  Y Y  \/ __ \|  |_> >
;   \____|__  /__|___|  /__|__|_|  (____  /   __/ 
;           \/        \/         \/     \/|__|    
;
;   Minimap by atom0s
;
;---------------------------------------------------------------------------------------------------
;
; This file contains the theme configurations for the 'windower' theme.
; Credits for the theme textures goes to the Windower team.
;
; For more information regarding themes, please refer to the documentation for Minimap:
; /docs/minimap/README.md
;
;---------------------------------------------------------------------------------------------------

[arrow]
w = 8
h = 12

[entity]
w = 4
h = 4

[entity.target]
w = 12
h = 12

[frame]
w = 248
h = 248
p = 25

[mask]
w = 200
h = 200